## optional config file
configfile: "config.yaml"

content = config["content"]
samples = config["samples"]
## all the output files you want to have
myppn = {'a': 2, 'b': 3, 'c':1}
mywt = {'a': "00:05:00", 'b': "00:15:00"}
mywt_default = "00:10:00"
def getwt(wcs, attempt):
    if wcs.s in mywt:
        return mywt[wcs.s]
    else:
        return mywt_default
    
knn_params = config["knn_params"]
print(knn_params)
    
## all the output files you want to have
rule all:
    input:
        expand("flag/pre_{s}.done", s = samples),
        expand("flag/first_{s}.done", s = samples)
## then set up the rules about how to generate them
rule pre:
    output:
        # s will be infered based on rule all output
        # here it will be a or b.
        # snakemake will run s=a and s=b in parallel if possible
        # touch will be automatically  generate the flag file
        # once the rule is done.
        a1 = touch("flag/pre_{s}.done"),
        a2 = touch("flag/pre_{s}_out2.done")
    params:
        knn = knn_params
    resources:
        ppn = lambda wildcards: myppn[wildcards.s],
        walltime=getwt
    conda:
        "sa2"
    log:
        "log/{s}.log"
    script:
        "pre.py"

# snakemake will know that it depends on the output of pre
# then the rule will run after pre
rule first:
    input:
        "flag/pre_{s}.done"
    output:
        touch("flag/first_{s}.done"),
        touch("flag/first_{s}_out2.done")
    log:
        "log/{s}.log"
    shell:
        """
        echo "first:" {content} {wildcards.s} 2>&1 >{log}
        """
