cluster-config: "profile/cluster.yaml"
cluster: "qsub -N {cluster.jobname} -l nodes={cluster.nodes}:ppn={resources.ppn},walltime={resources.walltime} -A {cluster.account} -q {cluster.queue} -M {cluster.email} -m {cluster.mailon} -j {cluster.jobout} -V "
jobs: 100
verbose: true
notemp: true
